apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: 676206922543.dkr.ecr.us-east-1.amazonaws.com/sravani433:tag
        ports:
        - containerPort: 80
